### ISSUE TITLE
turn off all Pi & HAT LEDs

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/huntsman-dome#15]

**Comment by AnthonyHorton** [comment]
All Raspberry Pi lights on `huntsmanpi010` (dome control Pi) have been disabled as per https://github.com/AstroHuntsman/huntsman-dome/issues/15#issuecomment-495435248

**Comment by AnthonyHorton** [comment]
Unless the Pimoroni Automation HAT Python library is used then all the Automation HAT LEDs are off unless explicitly turned on using, for example, the Pimroni `sn3218` library.

As we plan to use `gpiozero` instead of the Pimoroni `automationhat` library I am closing this as resolved.
