### ISSUE TITLE
add manual dome control & full stop via external 3-button switch

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/huntsman-dome#16]
Must include a safety lock-out e.g.:
https://www.tro-pacific.com/products/idec-key-selector-switch-maintained-2-position-n-o-n-c

**Comment by lspitler** [comment]
As @AnthonyHorton mentioned in meeting today, @fergusL think about re-doing the configuration anticipating this.

**Comment by AnthonyHorton** [comment]
Getting there...

![IMG_20190812_105714](https://user-images.githubusercontent.com/5875088/62849020-4a527880-bd21-11e9-9adb-899a01a89b60.jpg)

This doesn't actually require anything from our dome control software. It's a case of wiring things up then changing settings in the Altivar 12 motor driver. Specifically we want to make sure we're using '2-wire control' mode (pretty sure we already are) and assign one of the other digital inputs to 'Fast stop'.

**Comment by AnthonyHorton** [comment]
Done!
