### ISSUE TITLE
domehunter won't install on Raspberry Pi due to Python 3.7 requirement

### ISSUE THREAD

**Issue by AnthonyHorton** [AstroHuntsman/huntsman-dome#18]
When trying to install `domehunter` on a Raspberry Pi by running `python setup.py develop` in the top level `huntsman-dome` directory you get the error message `ERROR: domehunter requires Python 3.7 or later`.

The latest version of Python available via Berryconda is currently 3.6.6 which means it is not possible to install `domehunter` in a `conda` env on a Raspberry Pi because of this issue.

The requirement for Python 3.7 comes from the `huntsman-dome` `setup.cfg` file, which specifies a minimum python version of 3.7.  It's likely that the Python code itself would actually run without trouble on Python 3.6 so this problem could probably be fixed by simply changing the minimum Python version in `setup.cfg`.

**Comment by fergusL** [comment]
Yeah we discussed it here but didn't get added as part of that pr.
https://github.com/AstroHuntsman/huntsman-dome/pull/9#issuecomment-492497788
I think I've made the change already in either my open pr or in my rpi python code branch that I'll open a pr for tomorrow.
