### ISSUE TITLE
Communicate 'actual' dome azimuth back to TheSkyX

### ISSUE THREAD

**Issue by fergusL** [AstroHuntsman/huntsman-dome#30]
When the TheSkyX wants the dome at an azimuth, it sends the requests and waits for response indicating the move is complete. It then seems to query the dome for its current az and if it isn't where it requested it seems to get stuck in a cycle of checking if the 'gotoaz' command is complete.

The problem is the granularity of the encoder. If one tick is 36 degrees (for arguments sake) and the dome wants to go from 0 az to 70, at the moment it will go two ticks and stop at 72.

request az=70 -> command complete and az=72 -> getaz? expecting 70 getting 72 -> is command complete? -> yes -> getaz? expecting 70 getting 72 -> is command complete?

etc. 

I can't just round the az to what TheSkyX expects to hear within the context of the gotoAz call and keep the rpi internal dome az accurate, as TheSkyX seems to separately query the dome azimuth after the gotoAz call is complete.

If the encoder count is fine enough such that requesting an az of 70 results in arriving at an az or 70.05 we might be able to get away with rounding the internal dome az to 70... which is what TheSkyX is looking for.

**Comment by AnthonyHorton** [comment]
I think (hope?) that this behaviour depends on the dome settings in TheSkyX. TheSkyX has it's own idea of what is 'near enough' when it comes to dome positioning (based on the dome geometry settings).
