### ISSUE TITLE
tolerance window overshoot problem

### ISSUE THREAD

**Issue by fergusL** [AstroHuntsman/huntsman-dome#41]
Paranoid perhaps, but it's theoretically possible for this to go straight past the target position if tolerance is really small and/or the dome is rotating really fast so that it manages to pass through the target window in the interval between loop iterations. Then it would just keep rotating for another 360 degrees until it got to the target position again, at which point it might pass through again.

It would be more robust to instead check whether the current dome azimuth minus the target position is less/more than +/- the tolerance (less/more & +/- depending on movement direction). Then even if the dome overshoots the target window within one iteration it will still stop.

_Originally posted by @AnthonyHorton in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3Mjk1OTgyODEx/pull_request_reviews/more_threads_

**Comment by wtgee** [comment]
@fergusL is this closed now?
