### ISSUE TITLE
Question: why not the AutomationHat library?

### ISSUE THREAD

**Issue by wtgee** [AstroHuntsman/huntsman-dome#45]
@fergusL and @AnthonyHorton, I think you both mentioned you didn't like the [AutomationHat library](https://github.com/pimoroni/automation-hat), but what were the specific complaints?

Seems like we are doing a lot of custom managing of led lights and io handling (a la #44) that they have already done.

**Comment by AnthonyHorton** [comment]
@wtgee The main motivation for not using it was the desire to use gpiozero for the digital I/O, in order to make use of the callback functions, etc. The Automation HAT uses lower level GPIO libraries under the hood that don't provide that functionality, or at least not as easily.

**Comment by wtgee** [comment]
Got it. Makes sense to have the callback functions although I'm surprised they don't offer that.
